#!/usr/bin/env node
/**
 * Copy the ABIs of the contracts the offchain packages talk to into @intentos/intent-schema,
 * so the SDK, API, solvers and dashboard all speak to the same compiled surface.
 *
 *   npm run gen:abi     (after `npm run build -w @intentos/contracts`)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const SOURCES = [
  ["INTENT_REGISTRY_ABI", "contracts/IntentRegistry.sol/IntentRegistry.json"],
  ["SETTLEMENT_ABI", "contracts/IntentSettlement.sol/IntentSettlement.json"],
  ["SOLVER_REGISTRY_ABI", "contracts/SolverRegistry.sol/SolverRegistry.json"],
  ["RWA_REGISTRY_ABI", "contracts/RWARegistry.sol/RWARegistry.json"],
  ["POLICY_ENGINE_ABI", "contracts/PolicyEngine.sol/PolicyEngine.json"],
  ["ERC20_ABI", "contracts/mocks/MockERC20.sol/MockERC20.json"],
  ["DEX_ROUTER_ABI", "contracts/mocks/MockDexRouter.sol/MockDexRouter.json"],
];

const chunks = [
  "// Generated by scripts/gen-abi.mjs from the compiled contract artifacts. Do not edit by hand.",
  "",
];

for (const [name, artifactPath] of SOURCES) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts/artifacts", artifactPath), "utf8"));
  chunks.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
}

const out = join(root, "packages/intent-schema/src/abi.ts");
writeFileSync(out, chunks.join("\n"));
console.log(`wrote ${out}`);
