// Satisfies vercel.json "functions": "api/*.js" so GitHub deploys pass config
// validation. Real handlers are generated by `npm run build:api` during the build.
module.exports = function (_req, res) {
  res.statusCode = 204;
  res.end();
};
