// Satisfies vercel.json functions glob for GitHub deploys. Real handlers
// are generated by `npm run build:api` during the Vercel build.
module.exports = (req, res) => {
  res.statusCode = 204;
  res.end();
};
